### PR TITLE
Floating contributor count 

### LINKED ISSUE #619: 🐞[Bug]: Overflowing live floating-contributor element
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

The floating contributor activity element is not fitting correctly 

Image

### Expected behavior

I want to increase the frame size and adjust the elements.

Image

### Add ScreenShots

Image

### What browsers are you seeing the problem on?

Chrome

### Record

- [x] I have read the Contributing Guidelines
- [ ] Are you a GSSOC'25 contributor
- [x] I want to work on this issue

### PR DESCRIPTION
**Pull request by gmarav05**
## Description
Fixes more contributors count for different widths. 

Fixes #619 

## Type of Change

- [ ] New feature (e.g., new page, component, or functionality)
- [x] Bug fix (non-breaking change that fixes an issue)
- [x] UI/UX improvement (design, layout, or styling updates)
- [ ] Performance optimization (e.g., code splitting, caching)
- [ ] Documentation update (README, contribution guidelines, etc.)
- [ ] Other (please specify):

## Changes Made
Fixes more contributors count for different widths. 

## Dependencies

- List any new dependencies or tools required for this change.
- Mention any version updates or configurations that need to be considered.

## Checklist

- [x] My code follows the style guidelines of this project.
- [x] I have tested my changes across major browsers and devices
- [x] My changes do not generate new console warnings or errors .
- [x] I ran `npm run build` and attached screenshot(s) in this PR.
- [x] This is already assigned Issue to me, not an unassigned issue.

Before 

Screenshot 2025-10-02 at 11 19 09 PM

After 

Screenshot 2025-10-02 at 11 20 40 PM

### CODE REVIEW

**Comment by Condition00** [comment]
This will cause conflicts if merged before my branch because I completely removed the more keyword.

File: src/components/Community/index.tsx [hunk 1]
```diff
@@ -33,7 +33,7 @@ export const LandingCommunity: FC<Props> = ({ className }) => {
     {
       stat: githubReposCount,
       statText: githubReposCountText,
-      description: "Live public projects on RecodHive, demonstrating the power of open-source collaboration.",
+      description: "Live public projects on Recode Hive, demonstrating the power of open-source collaboration.",
```
Comment (iitzIrFan) [inline src/components/Community/index.tsx:36]: Revert this change.

File: src/components/Community/index.tsx [hunk 2]
```diff
@@ -129,7 +129,7 @@ export const LandingCommunity: FC<Props> = ({ className }) => {
               handleCardClick("https://github.com/recodehive");
             }
           }}
-          title="Click to visit RecodHive GitHub Organization"
+          title="Click to visit Recode Hive GitHub Organization"
```
Comment (iitzIrFan) [inline src/components/Community/index.tsx:132]: Same as above.

File: src/components/Community/index.tsx [hunk 3]
```diff
@@ -138,7 +138,7 @@ export const LandingCommunity: FC<Props> = ({ className }) => {
             loading="lazy"
           />
           <div className="landing-community__info-text">
-            Our developers are the core of RecodHive community. We take pride in
+            Our developers are the core of Recode Hive community. We take pride in
```
Comment (iitzIrFan) [inline src/components/Community/index.tsx:141]: same

File: src/components/Community/index.tsx [hunk 4]
```diff
@@ -147,7 +147,7 @@ export const LandingCommunity: FC<Props> = ({ className }) => {
             <span className="landing-community__link">
               contributors and maintainers
             </span>{" "}
-            powering RecodHive's growth.
+            powering Recode Hive's growth.
```
Comment (iitzIrFan) [inline src/components/Community/index.tsx:150]: same

File: src/database/projects/projects.tsx [hunk 5]
```diff
@@ -3,7 +3,7 @@ import { OurProjectsData } from "../../components/ourProjects";
 const projectsData: OurProjectsData = {
   tag: "Our Projects",
   title: "Explore Our Latest Projects and Innovations",
-  description: "Discover our diverse projects showcasing all the begineer friendly opensource contributions, innovative applications. Each project represents our commitment to excellence and continuous learning.",
+  description: "Discover our diverse projects showcasing all the beginner friendly opensource contributions, innovative applications. Each project represents our commitment to excellence and continuous learning.",
```
Comment (iitzIrFan) [inline src/database/projects/projects.tsx:6]: Do mention other issues that, you have solved in single PR.

**Review by iitzIrFan — CHANGES_REQUESTED** [review]

**Review by iitzIrFan — CHANGES_REQUESTED** [review]
Changes updated !
